# Generated by Django 6.0.3 on 2026-03-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_user_date_of_joining_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('leaves', 'Leave Management'), ('employees', 'Employees'), ('departments', 'Departments'), ('salary', 'Salary Details'), ('bank', 'Bank Details'), ('verification', 'Verification Details'), ('reports', 'Reports'), ('notifications', 'Notifications')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role__name', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
