# Generated by Django 4.2.7 on 2026-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetails',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
