# Generated by Django 4.2.7 on 2026-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_additionaldetails_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldetails',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
