# Generated by Django 5.2.11 on 2026-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_additionaldetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
