# Generated by Copilot on 2026-04-03
from django.db import migrations, models
import django.db.models.deletion


PERMISSION_SEEDS = [
    ("dashboard", "view", "dashboard_view", "View dashboard", "View dashboard"),
    ("user", "view", "user_view", "View users", "View users"),
    ("user", "add", "user_add", "Add users", "Add users"),
    ("user", "edit", "user_edit", "Edit users", "Edit users"),
    ("user", "delete", "user_delete", "Delete users", "Delete users"),
    ("user", "manage", "user_manage", "Manage users", "Manage users"),
    ("leave", "view", "leave_view", "View leave records", "View leave records"),
    ("leave", "add", "leave_apply", "Apply for leave", "Apply for leave"),
    ("leave", "edit", "leave_edit", "Edit leave records", "Edit leave records"),
    ("leave", "delete", "leave_delete", "Delete leave records", "Delete leave records"),
    ("leave", "approve", "leave_approve", "Approve leave", "Approve leave"),
    ("leave", "reject", "leave_reject", "Reject leave", "Reject leave"),
    ("leave", "manage", "leave_manage", "Manage leave workflow", "Manage leave workflow"),
    ("holiday", "view", "holiday_view", "View holidays", "View holidays"),
    ("holiday", "add", "holiday_add", "Create holidays", "Create holidays"),
    ("holiday", "edit", "holiday_edit", "Edit holidays", "Edit holidays"),
    ("holiday", "delete", "holiday_delete", "Delete holidays", "Delete holidays"),
    ("holiday", "manage", "holiday_manage", "Manage holidays", "Manage holidays"),
    ("report", "view", "report_view", "View reports", "View reports"),
    ("report", "manage", "report_manage", "Manage reports", "Manage reports"),
    ("system", "manage", "system_manage", "Manage system settings", "Manage system settings"),
    ("system", "role_manage", "role_manage", "Manage roles", "Manage roles"),
    ("system", "permission_manage", "permission_manage", "Manage permissions", "Manage permissions"),
]

ROLE_ASSIGNMENTS = {
    "Admin": {
        "dashboard_view", "user_view", "user_add", "user_edit", "user_delete", "user_manage",
        "leave_view", "leave_apply", "leave_edit", "leave_delete", "leave_approve", "leave_reject", "leave_manage",
        "holiday_view", "holiday_add", "holiday_edit", "holiday_delete", "holiday_manage",
        "report_view", "report_manage",
        "system_manage", "role_manage", "permission_manage",
    },
    "HR": {
        "dashboard_view", "user_view", "user_edit",
        "leave_view", "leave_apply", "leave_edit", "leave_approve", "leave_reject", "leave_manage",
        "holiday_view", "holiday_add", "holiday_edit", "holiday_delete", "holiday_manage",
        "report_view",
    },
    "Manager": {
        "dashboard_view", "user_view",
        "leave_view", "leave_approve", "leave_reject", "leave_manage",
        "holiday_view", "report_view",
    },
    "TL": {
        "dashboard_view", "user_view",
        "leave_view", "leave_apply", "leave_approve", "leave_reject", "leave_manage",
        "holiday_view",
    },
    "Employee": {
        "dashboard_view", "leave_view", "leave_apply", "holiday_view", "report_view",
    },
}


def seed_rbac(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    RBACPermission = apps.get_model("users", "RBACPermission")
    RolePermissionAssignment = apps.get_model("users", "RolePermissionAssignment")

    for module, action, codename, name, description in PERMISSION_SEEDS:
        RBACPermission.objects.get_or_create(
            codename=codename,
            defaults={
                "module": module,
                "action": action,
                "name": name,
                "description": description,
                "is_active": True,
            },
        )

    perm_map = {p.codename: p for p in RBACPermission.objects.all()}

    for role_name, codes in ROLE_ASSIGNMENTS.items():
        role = Role.objects.filter(name=role_name).first()
        if not role:
            continue
        for code in codes:
            permission = perm_map.get(code)
            if not permission:
                continue
            RolePermissionAssignment.objects.update_or_create(
                role=role,
                permission=permission,
                defaults={"is_enabled": True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="RBACPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module", models.CharField(choices=[("user", "User"), ("leave", "Leave"), ("holiday", "Holiday"), ("report", "Report"), ("dashboard", "Dashboard"), ("system", "System")], max_length=50)),
                ("action", models.CharField(choices=[("view", "View"), ("add", "Add"), ("edit", "Edit"), ("delete", "Delete"), ("approve", "Approve"), ("reject", "Reject"), ("manage", "Manage")], max_length=20)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "RBAC Permission",
                "verbose_name_plural": "RBAC Permissions",
                "ordering": ["module", "action"],
                "unique_together": {("module", "action")},
            },
        ),
        migrations.CreateModel(
            name="RolePermissionAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_assignments", to="users.rbacpermission")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rbac_permissions", to="users.role")),
            ],
            options={
                "verbose_name": "Role Permission Assignment",
                "verbose_name_plural": "Role Permission Assignments",
                "ordering": ["role__name", "permission__module", "permission__action"],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=150)),
                ("permission_code", models.CharField(blank=True, default="", max_length=100)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("status", models.CharField(choices=[("allowed", "Allowed"), ("denied", "Denied")], max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.user")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_rbac, migrations.RunPython.noop),
    ]
