# Generated by Copilot on 2026-04-03
from django.db import migrations


PERMISSION_SEEDS = [
    ("dashboard", "view", "dashboard_admin", "Admin dashboard", "Admin dashboard"),
    ("dashboard", "view", "dashboard_hr", "HR dashboard", "HR dashboard"),
    ("dashboard", "view", "dashboard_manager", "Manager dashboard", "Manager dashboard"),
    ("dashboard", "view", "dashboard_employee", "Employee dashboard", "Employee dashboard"),
    ("user", "view", "user_view", "View users", "View users"),
    ("user", "add", "user_create", "Create users", "Create users"),
    ("user", "edit", "user_update", "Update users", "Update users"),
    ("user", "delete", "user_delete", "Delete users", "Delete users"),
    ("user", "activate", "user_activate", "Activate users", "Activate users"),
    ("user", "deactivate", "user_deactivate", "Deactivate users", "Deactivate users"),
    ("user", "manage", "user_assign_role", "Assign roles to users", "Assign roles to users"),
    ("role", "view", "role_view", "View roles", "View roles"),
    ("role", "add", "role_create", "Create roles", "Create roles"),
    ("role", "edit", "role_update", "Update roles", "Update roles"),
    ("role", "delete", "role_delete", "Delete roles", "Delete roles"),
    ("role", "manage", "role_assign_permissions", "Assign permissions to roles", "Assign permissions to roles"),
    ("role", "view", "permission_view", "View permissions", "View permissions"),
    ("role", "manage", "permission_assign", "Assign permissions", "Assign permissions"),
    ("leave", "view", "leave_view_own", "View own leave requests", "View own leave requests"),
    ("leave", "add", "leave_apply", "Apply for leave", "Apply for leave"),
    ("leave", "edit", "leave_update_own", "Update own leave requests", "Update own leave requests"),
    ("leave", "delete", "leave_delete_own", "Delete own leave requests", "Delete own leave requests"),
    ("leave", "delete", "leave_cancel", "Cancel leave request", "Cancel leave request"),
    ("leave", "view", "leave_view_all", "View all leave requests", "View all leave requests"),
    ("leave", "approve", "leave_approve", "Approve leave requests", "Approve leave requests"),
    ("leave", "reject", "leave_reject", "Reject leave requests", "Reject leave requests"),
    ("leave", "view", "leave_policy_view", "View leave policy", "View leave policy"),
    ("leave", "add", "leave_policy_create", "Create leave policy", "Create leave policy"),
    ("leave", "edit", "leave_policy_update", "Update leave policy", "Update leave policy"),
    ("leave", "delete", "leave_policy_delete", "Delete leave policy", "Delete leave policy"),
    ("leave", "view", "leave_balance_view", "View leave balances", "View leave balances"),
    ("leave", "edit", "leave_balance_update", "Update leave balances", "Update leave balances"),
    ("holiday", "view", "holiday_view", "View holidays", "View holidays"),
    ("holiday", "add", "holiday_create", "Create holidays", "Create holidays"),
    ("holiday", "edit", "holiday_update", "Update holidays", "Update holidays"),
    ("holiday", "delete", "holiday_delete", "Delete holidays", "Delete holidays"),
    ("report", "view", "report_view", "View reports", "View reports"),
    ("report", "view", "report_export", "Export reports", "Export reports"),
    ("team", "view", "team_view", "View teams", "View teams"),
    ("team", "manage", "team_manage", "Manage teams", "Manage teams"),
    ("system", "view", "settings_view", "View settings", "View settings"),
    ("system", "edit", "settings_update", "Update settings", "Update settings"),
    ("system", "view", "audit_view", "View audit logs", "View audit logs"),
]

ROLE_ASSIGNMENTS = {
    "Admin": {
        "dashboard_admin",
        "user_view", "user_create", "user_update", "user_delete", "user_activate", "user_deactivate", "user_assign_role",
        "role_view", "role_create", "role_update", "role_delete", "role_assign_permissions", "permission_view", "permission_assign",
        "leave_view_own", "leave_apply", "leave_update_own", "leave_delete_own", "leave_cancel", "leave_view_all", "leave_approve", "leave_reject",
        "leave_policy_view", "leave_policy_create", "leave_policy_update", "leave_policy_delete", "leave_balance_view", "leave_balance_update",
        "holiday_view", "holiday_create", "holiday_update", "holiday_delete",
        "report_view", "report_export",
        "team_view", "team_manage",
        "settings_view", "settings_update",
        "audit_view",
    },
    "HR": {
        "dashboard_hr",
        "user_view", "user_create", "user_update", "user_activate", "user_deactivate", "user_assign_role",
        "leave_view_all", "leave_approve", "leave_reject",
        "leave_policy_view", "leave_balance_view",
        "holiday_view", "holiday_create", "holiday_update", "holiday_delete",
        "report_view", "report_export",
        "team_view", "team_manage",
        "settings_view", "settings_update",
        "audit_view",
    },
    "Manager": {
        "dashboard_manager",
        "leave_view_all", "leave_approve", "leave_reject",
        "leave_policy_view", "leave_balance_view",
        "holiday_view",
        "report_view", "report_export",
        "team_view", "team_manage",
    },
    "TL": {
        "dashboard_manager",
        "leave_view_own", "leave_apply", "leave_view_all", "leave_approve", "leave_reject",
        "leave_policy_view", "leave_balance_view",
        "holiday_view",
        "team_view",
    },
    "Employee": {
        "dashboard_employee",
        "leave_view_own", "leave_apply", "leave_update_own", "leave_delete_own", "leave_cancel",
        "leave_balance_view",
        "holiday_view",
    },
}


def seed_exact_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    RBACPermission = apps.get_model("users", "RBACPermission")
    RolePermissionAssignment = apps.get_model("users", "RolePermissionAssignment")

    for module, action, codename, name, description in PERMISSION_SEEDS:
        RBACPermission.objects.get_or_create(
            codename=codename,
            defaults={
                "module": module,
                "action": action,
                "name": name,
                "description": description,
                "is_active": True,
            },
        )

    permission_map = {permission.codename: permission for permission in RBACPermission.objects.all()}

    for role_name, codes in ROLE_ASSIGNMENTS.items():
        role = Role.objects.filter(name=role_name).first()
        if not role:
            continue
        for code in codes:
            permission = permission_map.get(code)
            if not permission:
                continue
            RolePermissionAssignment.objects.update_or_create(
                role=role,
                permission=permission,
                defaults={"is_enabled": True},
            )


def drop_module_action_unique_constraint(apps, schema_editor):
    RBACPermission = apps.get_model("users", "RBACPermission")
    try:
        schema_editor.alter_unique_together(RBACPermission, {("codename",)})
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rbac_system"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rbacpermission",
            unique_together=set(),
        ),
        migrations.RunPython(seed_exact_permissions, migrations.RunPython.noop),
    ]
