# Generated by Codex on 2026-04-03
from django.db import migrations


REQUIRED_TL_PERMISSIONS = {
    "leave_approve",
    "leave_reject",
}


def grant_tl_leave_action_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    RBACPermission = apps.get_model("users", "RBACPermission")
    RolePermissionAssignment = apps.get_model("users", "RolePermissionAssignment")

    tl_role = Role.objects.filter(name="TL").first()
    if not tl_role:
        return

    permissions = RBACPermission.objects.filter(codename__in=REQUIRED_TL_PERMISSIONS)
    for permission in permissions:
        RolePermissionAssignment.objects.update_or_create(
            role=tl_role,
            permission=permission,
            defaults={"is_enabled": True},
        )


def revoke_tl_leave_action_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    RBACPermission = apps.get_model("users", "RBACPermission")
    RolePermissionAssignment = apps.get_model("users", "RolePermissionAssignment")

    tl_role = Role.objects.filter(name="TL").first()
    if not tl_role:
        return

    permissions = RBACPermission.objects.filter(codename__in=REQUIRED_TL_PERMISSIONS)
    RolePermissionAssignment.objects.filter(
        role=tl_role,
        permission__in=permissions,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_exact_permission_catalog"),
    ]

    operations = [
        migrations.RunPython(
            grant_tl_leave_action_permissions,
            revoke_tl_leave_action_permissions,
        ),
    ]
