# Generated by Django 4.2.7 on 2026-04-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydeduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarydeduction',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='leaves.leaverequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, to='users.department'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='applicable_roles',
            field=models.ManyToManyField(blank=True, to='users.role'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if this policy applies to all', to='users.department'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveallocationledger',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='leaves.employeeleaveallocation'),
        ),
        migrations.AddField(
            model_name='leaveallocationledger',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocation_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveallocationledger',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_ledger_entries', to='leaves.leavetypeconfig'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='applicable_departments',
            field=models.ManyToManyField(blank=True, to='users.department'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leaves.leavetypeconfig'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['employee', 'deduction_month'], name='leaves_sala_employe_5fc1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['is_processed'], name='leaves_sala_is_proc_446c70_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveallocationledger',
            index=models.Index(fields=['employee', 'year'], name='leaves_leav_employe_a65220_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveallocationledger',
            index=models.Index(fields=['leave_type', 'year'], name='leaves_leav_leave_t_f736a7_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_active'], name='leaves_holi_date_a82392_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['year', 'holiday_type'], name='leaves_holi_year_f1f33f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
        migrations.AddIndex(
            model_name='employeeleaveallocation',
            index=models.Index(fields=['employee', 'year'], name='leaves_empl_employe_ffcfac_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeleaveallocation',
            index=models.Index(fields=['leave_type', 'year'], name='leaves_empl_leave_t_5257e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleaveallocation',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
