# Generated by Django 6.0.3 on 2026-03-09 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_department_rename_applied_at_leaverequest_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='short_leave',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='urgent_leave',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='applied_to',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('SHORT', 'Short Leave')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='short_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='short_session',
            field=models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.FloatField(default=12),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('TL_PENDING', 'TL Pending'), ('HR_PENDING', 'HR Pending'), ('MANAGER_PENDING', 'Manager Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='TL_PENDING', max_length=30),
        ),
    ]
