# Generated by Django 4.2.7 on 2026-03-11 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0003_delete_department_remove_leavebalance_short_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Diwali, Republic Day, Christmas', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('holiday_type', models.CharField(choices=[('NATIONAL', '🇮🇳 National Holiday'), ('RELIGIOUS', '🕉️ Religious Holiday'), ('REGIONAL', '📍 Regional Holiday'), ('COMPANY', '🏢 Company Holiday'), ('BANK', '🏦 Bank Holiday'), ('OTHER', '🎉 Other')], default='NATIONAL', max_length=20)),
                ('date', models.DateField(help_text='Date of holiday')),
                ('end_date', models.DateField(blank=True, help_text='For multi-day holidays like Diwali', null=True)),
                ('year', models.IntegerField(editable=False)),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year?')),
                ('recurring_rule', models.CharField(blank=True, help_text="e.g., 'second monday of october'", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_to_all', models.BooleanField(default=True)),
                ('applicable_locations', models.CharField(blank=True, help_text='Specific locations/cities if applicable', max_length=200)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_type', models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, to='users.department')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='leaves_holi_date_a82392_idx'), models.Index(fields=['year', 'holiday_type'], name='leaves_holi_year_f1f33f_idx')],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
