# Generated by Django 4.2.7 on 2026-03-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='attachment',
            field=models.FileField(blank=True, help_text='Medical report, marriage card, or other supporting document', null=True, upload_to='leave_attachments/'),
        ),
    ]
