# Generated by Django 4.2.7 on 2026-03-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_holiday_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='attachment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Medical report, marriage card, or other supporting document', null=True, upload_to='leave_attachments/'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='applicable_locations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(blank=True, help_text='For multi-day holidays', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='recurring_rule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Urgent', 'Urgent Leave'), ('Married', 'Married Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='short_session',
            field=models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half'), ('AM', 'AM'), ('PM', 'PM')], max_length=20, null=True),
        ),
    ]
