# Generated by Django 4.2.7 on 2026-03-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_remove_holiday_attachment_leaverequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='TL_PENDING', max_length=30),
        ),
    ]
