# Generated by Django 4.2.7 on 2026-03-16 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0007_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='leave_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
