# Generated by Django 4.2.7 on 2026-03-20 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_leaverequest_approval_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last date when monthly accrual was added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='monthly_accrual_rate',
            field=models.FloatField(default=1.5, help_text='Leaves earned per month'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_accrued',
            field=models.FloatField(default=0, help_text='Total leaves earned since joining (1.5 per month)'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_paid_taken',
            field=models.FloatField(default=0, help_text='Total paid leaves used (deducted from balance)'),
        ),
    ]
