# Generated by Django 4.2.7 on 2026-03-20 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0010_alter_leavebalance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_days', models.FloatField(help_text='Number of unpaid days for this leave')),
                ('deduction_amount', models.DecimalField(decimal_places=2, help_text='Amount to deduct from salary', max_digits=10)),
                ('deduction_month', models.DateField(help_text='Month of deduction (first day of month)')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this deduction has been included in payroll')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this was processed in payroll', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this deduction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='leaves.leaverequest')),
            ],
            options={
                'ordering': ['-deduction_month', 'employee__email'],
                'indexes': [models.Index(fields=['employee', 'deduction_month'], name='leaves_sala_employe_5fc1e0_idx'), models.Index(fields=['is_processed'], name='leaves_sala_is_proc_446c70_idx')],
            },
        ),
    ]
