# Generated by Django 4.2.7 on 2026-03-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_salarydeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='balance_deducted_at',
            field=models.DateTimeField(blank=True, help_text='When paid days were deducted from balance', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_fully_paid',
            field=models.BooleanField(default=True, help_text='Whether this leave is fully covered by balance'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='paid_days',
            field=models.FloatField(default=0, help_text='Number of days covered by leave balance (paid)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unpaid_days',
            field=models.FloatField(default=0, help_text='Number of days exceeding balance (unpaid, salary deducted)'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
