# Generated by Django 4.2.7 on 2026-03-23 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_user_designation'),
        ('leaves', '0012_leaverequest_balance_deducted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#00c6d4', help_text='Hex color used in UI badges', max_length=7)),
                ('days_per_year', models.FloatField(default=12, help_text='Total days allowed per calendar year')),
                ('is_accrual_based', models.BooleanField(default=False, help_text='True = accrues monthly | False = full quota on Jan 1')),
                ('monthly_accrual', models.FloatField(default=1.0, help_text='Days earned per month (used only if is_accrual_based=True)')),
                ('is_paid', models.BooleanField(default=True, help_text='False = unpaid leave, salary will be deducted')),
                ('max_consecutive_days', models.IntegerField(default=0, help_text='Max days in a single request. 0 = no limit')),
                ('advance_notice_days', models.IntegerField(default=0, help_text='Employee must apply N days in advance. 0 = same day allowed')),
                ('document_required_after', models.IntegerField(default=0, help_text='Require document if leave exceeds N days. 0 = never required')),
                ('carry_forward', models.BooleanField(default=False)),
                ('carry_forward_limit', models.FloatField(default=0, help_text='Max days to carry to next year. 0 = carry all remaining')),
                ('applicable_to', models.CharField(choices=[('ALL', 'All Employees'), ('ROLES', 'Specific Roles'), ('DEPARTMENTS', 'Specific Departments')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, to='users.department')),
                ('applicable_roles', models.ManyToManyField(blank=True, to='users.role')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Type Config',
                'verbose_name_plural': 'Leave Type Configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_days_per_request', models.IntegerField(default=5, help_text='Max days an employee can request at once')),
                ('min_advance_days', models.IntegerField(default=1, help_text='Must apply at least N days before leave starts')),
                ('weekend_counts_as_leave', models.BooleanField(default=False, help_text='If True, Sat/Sun between leave days are counted')),
                ('holiday_counts_as_leave', models.BooleanField(default=False, help_text='If True, public holidays in leave range are counted')),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_short_leave', models.BooleanField(default=True)),
                ('approval_threshold', models.IntegerField(default=2, help_text='Votes needed to approve a leave (your voting system uses 2)')),
                ('is_default', models.BooleanField(default=False, help_text='Only one policy can be default. All employees use this unless overridden.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, help_text='Leave blank if this policy applies to all', to='users.department')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_days', models.FloatField(default=0, help_text='Days given to this employee for this leave type this year')),
                ('used_days', models.FloatField(default=0, help_text='Days actually consumed (approved leaves)')),
                ('carried_forward', models.FloatField(default=0, help_text='Days carried over from previous year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leaves.leavetypeconfig')),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leaves_empl_employe_ffcfac_idx'), models.Index(fields=['leave_type', 'year'], name='leaves_empl_leave_t_5257e3_idx')],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
