# Generated by Django 5.2.11 on 2026-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_leavetypeconfig_leavepolicy_employeeleaveallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500, null=True),
        ),
    ]
