# Generated by Django 4.2.7 on 2026-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypeconfig',
            name='starting_month',
            field=models.IntegerField(default=4, help_text='Month when leave year starts (1=Jan, 4=Apr, etc.)'),
        ),
    ]
