# Generated by Django 4.2.7 on 2026-04-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_leavetypeconfig_starting_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
