# Generated by Django 4.2.7 on 2026-04-07 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0016_remove_legacy_leave_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year_start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4)),
                ('default_casual_quota', models.FloatField(default=12)),
                ('default_sick_quota', models.FloatField(default=8)),
                ('default_annual_quota', models.FloatField(default=18)),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('grace_period_minutes', models.PositiveIntegerField(default=10)),
                ('auto_deduction_enabled', models.BooleanField(default=False)),
                ('auto_deduction_after_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic & Leave Settings',
                'verbose_name_plural': 'Academic & Leave Settings',
            },
        ),
    ]
