# Generated by Django 5.2.12 on 2026-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_academicleavesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicleavesettings',
            name='annual_leave_quota',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='event_date',
            field=models.DateField(blank=True, help_text='Relevant event date for document-backed leave (e.g. marriage, birth)', null=True),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='When this leave type was last consumed', null=True),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='lifetime_used',
            field=models.FloatField(default=0, help_text='Total lifetime usage for capped/special leaves'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_verified_at',
            field=models.DateTimeField(blank=True, help_text='When an attached document was verified by approver/admin', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='eligibility_checked',
            field=models.BooleanField(default=False, help_text='Whether special leave eligibility checks were completed'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='applicable_gender',
            field=models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='max_lifetime_usage',
            field=models.FloatField(default=0, help_text='Lifetime cap for special leaves. 0 = no lifetime cap'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='min_service_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum completed service days required'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='quota_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ANNUAL_POOL', 'Annual Pool'), ('SPECIAL_EVENT', 'Special Event'), ('MATERNITY_PATERNITY', 'Maternity/Paternity')], default='STANDARD', help_text='How this leave type consumes quota', max_length=30),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='requires_document',
            field=models.BooleanField(default=False, help_text='Whether a supporting document is mandatory'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='usage_resets_yearly',
            field=models.BooleanField(default=True, help_text='Whether usage resets every leave year'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('HALF_DAY', 'Half Day Leave'), ('SHORT_LEAVE', 'Short Leave'), ('MARRIAGE', 'Marriage Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Urgent', 'Urgent Leave'), ('Married', 'Married Leave')], max_length=20),
        ),
    ]
