# Generated by Django 5.2.12 on 2026-04-07 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('leaves', '0016_remove_legacy_leave_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllocationLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('annual_quota', models.FloatField(default=0)),
                ('allocated_quota', models.FloatField(default=0)),
                ('used_leaves', models.FloatField(default=0)),
                ('remaining_leaves', models.FloatField(default=0)),
                ('action', models.CharField(default='PRORATED_ALLOCATION', max_length=50)),
                ('note', models.TextField(default='Pro-rated allocation generated on employee onboarding')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='leaves.employeeleaveallocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocation_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_ledger_entries', to='leaves.leavetypeconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leaves_leav_employe_a65220_idx'), models.Index(fields=['leave_type', 'year'], name='leaves_leav_leave_t_f736a7_idx')],
            },
        ),
    ]
