# Generated by Django 5.2.12 on 2026-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0019_leaveallocationledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicleavesettings',
            name='show_only_monthly_in_balance',
            field=models.BooleanField(default=True, help_text='If enabled, employee balance widgets show only monthly-accrual leave types'),
        ),
    ]
