# Generated by Django 5.2.12 on 2026-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0019_leaveallocationledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('URGENT', 'Urgent Leave'), ('HALF_DAY', 'Half Day Leave'), ('SHORT_LEAVE', 'Short Leave'), ('MARRIAGE', 'Marriage Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Urgent', 'Urgent Leave'), ('Married', 'Married Leave')], max_length=20),
        ),
    ]
