# Generated by Django 4.2.7 on 2026-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0021_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager_already_counted',
            field=models.BooleanField(default=False, help_text="Track if manager's approval vote was counted"),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_already_counted_reject',
            field=models.BooleanField(default=False, help_text="Track if manager's rejection vote was counted"),
        ),
    ]
