# Generated by Django 4.2.7 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0022_leaverequest_manager_already_counted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='hr_remark',
            field=models.TextField(blank=True, default='', help_text='Optional remark provided by HR during approval/rejection.'),
        ),
    ]
