# Generated by Django 4.2.7 on 2026-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0023_leaverequest_hr_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='tl_remark',
            field=models.TextField(blank=True, default='', help_text='Optional remark provided by Team Lead during approval/rejection.'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_remark',
            field=models.TextField(blank=True, default='', help_text='Optional remark provided by Manager during approval/rejection.'),
        ),
    ]
