# Generated by Django 4.2.7 on 2026-04-10 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0024_leaverequest_tl_remark_leaverequest_manager_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='event_date',
            field=models.DateField(blank=True, help_text='Relevant event date for document-backed leave (e.g. marriage, birth)', null=True),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='When this leave type was last consumed', null=True),
        ),
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='lifetime_used',
            field=models.FloatField(default=0, help_text='Total lifetime usage for capped/special leaves'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_verified_at',
            field=models.DateTimeField(blank=True, help_text='When an attached document was verified by approver/admin', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='eligibility_checked',
            field=models.BooleanField(default=False, help_text='Whether special leave eligibility checks were completed'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='applicable_gender',
            field=models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='max_lifetime_usage',
            field=models.FloatField(default=0, help_text='Lifetime cap for special leaves. 0 = no lifetime cap'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='min_service_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum completed service days required'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='quota_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ANNUAL_POOL', 'Annual Pool'), ('SPECIAL_EVENT', 'Special Event'), ('MATERNITY_PATERNITY', 'Maternity/Paternity')], default='STANDARD', help_text='How this leave type consumes quota', max_length=30),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='requires_document',
            field=models.BooleanField(default=False, help_text='Whether a supporting document is mandatory'),
        ),
        migrations.AddField(
            model_name='leavetypeconfig',
            name='usage_resets_yearly',
            field=models.BooleanField(default=True, help_text='Whether usage resets every leave year'),
        ),
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year_start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4)),
                ('default_casual_quota', models.FloatField(default=12)),
                ('default_sick_quota', models.FloatField(default=8)),
                ('default_annual_quota', models.FloatField(default=18)),
                ('annual_leave_quota', models.FloatField(default=12)),
                ('show_only_monthly_in_balance', models.BooleanField(default=True, help_text='If enabled, employee balance widgets show only monthly-accrual leave types')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('grace_period_minutes', models.PositiveIntegerField(default=10)),
                ('auto_deduction_enabled', models.BooleanField(default=False)),
                ('auto_deduction_after_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Settings',
                'verbose_name_plural': 'Leave Settings',
            },
        ),
    ]
