# Generated by Django 4.2.7 on 2026-04-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_academicleavesettings'),
        ('leaves', '0025_employeeleaveallocation_event_date_and_more'),
    ]

    operations = [
    ]
