# Generated by Django on 2026-04-14
from django.db import migrations
from datetime import date, timedelta


def recalculate_leave_durations(apps, schema_editor):
    LeaveRequest = apps.get_model('leaves', 'LeaveRequest')
    LeavePolicy = apps.get_model('leaves', 'LeavePolicy')
    Holiday = apps.get_model('leaves', 'Holiday')
    
    # Get default policy
    policy = LeavePolicy.objects.filter(is_default=True, is_active=True).first()
    
    for leave in LeaveRequest.objects.filter(duration='FULL'):
        if not leave.start_date:
            continue
        
        end_date = leave.end_date or leave.start_date
        total_days = 0
        current_date = leave.start_date
        
        # Get holidays for this period if policy says not to count them
        holidays = []
        if policy and not policy.holiday_counts_as_leave:
            holidays = list(Holiday.objects.filter(
                date__gte=leave.start_date,
                date__lte=end_date,
                is_active=True
            ))
        
        while current_date <= end_date:
            is_weekend = current_date.weekday() >= 5
            
            if is_weekend:
                if policy and policy.weekend_counts_as_leave:
                    total_days += 1
            else:
                total_days += 1
            
            # Subtract holiday if it shouldn't count
            if policy and not policy.holiday_counts_as_leave:
                if any(h.date == current_date for h in holidays):
                    total_days -= 1
            
            current_date += timedelta(days=1)
        
        # Update leave duration if you have a field for it
        # For now, just update the leave_duration_days property calculation
        print(f"Leave {leave.id}: calculated {total_days} days")


class Migration(migrations.Migration):
    dependencies = [
        ('leaves', '0025_employeeleaveallocation_event_date_and_more'),
    ]

    operations = [
        migrations.RunPython(recalculate_leave_durations, migrations.RunPython.noop),
    ]